CREATE TABLE `bugs` (
	`id` integer PRIMARY KEY NOT NULL,
	`test_rail_project_id` integer NOT NULL,
	`jira_project_id` text NOT NULL,
	`month` text NOT NULL,
	`year` text NOT NULL,
	`total_bugs` integer NOT NULL,
	`dev_bugs` integer NOT NULL,
	`prod_bugs` integer NOT NULL,
	`bug_resolution` real NOT NULL,
	`stories_resolved` integer NOT NULL,
	`defect_severity_index` real NOT NULL,
	`createdAt` text DEFAULT 'datetime("now")' NOT NULL,
	`updatedAt` text DEFAULT 'datetime("now")' NOT NULL
);
--> statement-breakpoint
CREATE TABLE `tests` (
	`id` integer PRIMARY KEY NOT NULL,
	`test_rail_project_id` integer NOT NULL,
	`jira_project_id` text NOT NULL,
	`month` text NOT NULL,
	`year` text NOT NULL,
	`total_tests` integer NOT NULL,
	`automated_tests` integer NOT NULL,
	`manual_tests` integer NOT NULL,
	`accessibility_tests` integer NOT NULL,
	`data_validation_tests` integer NOT NULL,
	`e2e_tests` integer NOT NULL,
	`functional_tests` integer NOT NULL,
	`integration_tests` integer NOT NULL,
	`performance_tests` integer NOT NULL,
	`load_tests` integer NOT NULL,
	`regression_tests` integer NOT NULL,
	`security_tests` integer NOT NULL,
	`smoke_tests` integer NOT NULL,
	`unit_tests` integer NOT NULL,
	`non_functional_tests` integer NOT NULL,
	`other_tests` integer NOT NULL,
	`createdAt` text DEFAULT 'datetime("now")' NOT NULL,
	`updatedAt` text DEFAULT 'datetime("now")' NOT NULL
);
