// Generated by Xata Codegen 0.28.3. Please do not edit.
import { buildClient } from "@xata.io/client";
import type {
  BaseClientOptions,
  SchemaInference,
  XataRecord,
} from "@xata.io/client";

const tables = [
  {
    name: "metrics",
    columns: [
      { name: "month", type: "string" },
      { name: "year", type: "string" },
      { name: "total_bugs", type: "int" },
      { name: "dev_bugs", type: "int" },
      { name: "prod_bugs", type: "int" },
    ],
  },
] as const;

export type SchemaTables = typeof tables;
export type InferredTypes = SchemaInference<SchemaTables>;

export type Metrics = InferredTypes["metrics"];
export type MetricsRecord = Metrics & XataRecord;

export type DatabaseSchema = {
  metrics: MetricsRecord;
};

const DatabaseClient = buildClient();

const defaultOptions = {
  databaseURL:
    "https://realed-s-workspace-i7sf28.us-east-1.xata.sh/db/qa-dashboard",
};

export class XataClient extends DatabaseClient<DatabaseSchema> {
  constructor(options?: BaseClientOptions) {
    super({ ...defaultOptions, ...options }, tables);
  }
}

let instance: XataClient | undefined = undefined;

export const getXataClient = () => {
  if (instance) return instance;

  instance = new XataClient();
  return instance;
};
